---
abstract: "A bundle to install all of Theory's favorite modules"
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
configure_requires:
  Module::Build: 0.2701
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bundle-Theory
provides:
  Bundle::Theory:
    file: lib/Bundle/Theory.pm
    version: 1.08
  Bundle::Theory::Apache:
    file: lib/Bundle/Theory/Apache.pm
    version: 1.08
  Bundle::Theory::Apache2:
    file: lib/Bundle/Theory/Apache2.pm
    version: 1.08
recommends:
  Test::Pod: 1.41
resources:
  license: http://dev.perl.org/licenses/
version: 1.08
